# Generated by Django 5.0.1 on 2024-02-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='instructions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='recipe_pics'),
        ),
    ]
