# Generated by Django 5.0.1 on 2024-02-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_description_recipe_instructions_recipe_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(db_column='description'),
        ),
    ]
