# Generated by Django 5.0.1 on 2024-02-06 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_instructions_recipe_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='instructions',
        ),
    ]
